
runtime: python39
instance_class: F1
handlers:
- url: /.*
  script: auto

env_variables:
  IS_PRODUCTION: "true"
  
automatic_scaling:
  target_cpu_utilization: 0.7
  min_instances: 1
  max_instances: 2
  min_pending_latency: 500ms
  max_concurrent_requests: 30