
runtime: python311
instance_class: F1
handlers:
- url: /.*
  script: auto

env_variables:
  IS_PRODUCTION: "true"
  IS_UAT: "false"
  GRAPH_VERSION: "v19"

entrypoint: gunicorn -b :8080 -w 1 main:app

automatic_scaling:
  max_instances: 2