
runtime: python311
instance_class: F1
handlers:
- url: /.*
  script: auto

env_variables:
  IS_PRODUCTION: "true"
  IS_UAT: "false"
  GRAPH_VERSION: "v26"

entrypoint: gunicorn -b :8080 main:app --timeout 90 --workers 1 --threads 8

automatic_scaling:
  max_instances: 2

inbound_services:
- warmup