glitches_names = [
    # Glitches: Goomba Region
    "PrologueGelEarly",
    "ReverseGoombaKingBridge",
    "GoombaVillageEntryFenceClip",
    "GoombaVillageNpcLureExit",
    "ClippyLedgeStarPiece",
    "JumplessFireFlower",
    "HammerlessJrPlaygroundLaki",
    "GoombaVillageLakiExit",
    "PrologueSushieGlitchKsj",
    "PrologueSushieGlitchUltraBootsLaki",

    # Glitches: Toad Town
    "BlueHouseSkip",
    "BlueHouseSkipLaki",
    "BlueHouseSkipToadLure",
    "JumplessDaneTLetters",
    "BowlessToyBoxHammer",
    "BowlessToyBoxHammerlessLure",
    "EarlyStoreroomParakarry",
    "EarlyStoreroomHammer",
    "EarlyStoreroomHammerlessLure",
    "WhaleEarly",
    "SushielessToadTownStarPiece",
    "ToadTownSushieGlitchGearless",
    "ToadTownSushieGlitch",
    "ToadTownSushieGlitchFullGear",

    # Glitches: Shooting Star Summit
    "JumplessSummitClimb",

    # Glitches: Toad Town Tunnels
    "ClippyBootsStoneBlockSkip",
    "ClippyBootsMetalBlockSkip",
    "IslandPipeBlooperSkip",
    "JumplessIslandPipe",
    "ParakarrylessSewerStarPiece",
    "ClippySewersUpgradeBlock",
    "SewerBlocksWithoutUltraBoots",
    "Chapter7BridgeWithSuperBoots",
    "FirstBlockToShiverCityWithoutSuperBoots",
    "BlocksToShiverCityWithKooperShellItemThrow",
    "SewerYellowBlockWithUltraBoots",
    "JumplessSewerShootingStar",

    # Glitches: Plesant Path
    "KooperlessPleasantPathStarPiece",
    "PleasantPathClippyTraversal",
    "HammerlessPleasantPathBridgeUltraBootsParakarry",
    "InvisibleBridgeClipLzs",
    "InvisibleBridgeClipLaki",
    "KooperlessPleasantPathThunderBolt",
    "JumplessKoopaVillageBluePipe",

    # Glitches: Koopa Bros Fortress
    "BombettelessKbfFpPlusLZS",
    "BombettelessKbfFpPlusLaki",
    "LakiJailbreak",
    "BombettelessRightFortressJailKey",
    "WaterStaircaseSkip",

    # Glitches: Mt. Rugged
    "MtRuggedQuakeHammerAndLetterWithLaki",
    "MtRuggedQuakeHammerRoomJumplessClippy",
    "ParakarrylessMtRuggedSeed",
    "ParakarrylessMtRuggedSeedClippy",
    "BuzzarGapSkipClippy",
    "ParakarrylessMtRuggedStarPiece",
    "ParakarrylessMtRuggedStarPieceClippy",
    "MtRuggedCoinsWithKooper",
    "MtRuggedStationJumplessClimbBombette",
    "MtRuggedStationJumplessClimbLaki",
    "MtRuggedStationJumplessClimbLakiBlockClip",
    "JumplessMtRuggedTrainPlatformParakarry",

    # Glitches: Dry Dry Desert
    "DesertBrickBlockItemWithParakarry",
    "JumplessAttackFXC",
    "EarlyRuinsLakiJump",
    "EarlyRuinsUltraBoots",

    # Glitches: Dry Dry Ruins
    "ArtifactJumpLaki",
    "ArtifactJumpUltraBoots",
    "RuinsKeyLakiJump",
    "ParakarrylessSecondSandRoomUltraBoots",
    "ParakarrylessSecondSandRoomNormalBoots",
    "RuinsBombWallSkip",
    "ParakarrylessSuperHammerRoomUltraBoots",
    "ParakarrylessSuperHammerRoomNormalBoots",
    "RuinsLocksSkipClippy",
    "RuinsPuzzleSolutionEarly",
    "RuinsStoneSkip",

    # Glitches: Boo's Mansion
    "ForeverForestBackwards",
    "RecordSkipNoBombettePush",
    "RecordSkipBombettePush",
    "BoosPortraitWithKooper",
    "BoosPortraitWithLaki",
    "JumplessMansionEntry",

    # Glitches: Gusty Gulch
    "GustyGulchGateSkipLZS",
    "GustyGulchGateSkipLaki",
    "KooperlessGustyGulchDizzyDialJump",
    "KooperlessGustyGulchDizzyDialLaki",
    "KooperlessGustyGulchDizzyDialParakarry",
    "GustyGulchGapSkip",
    "GustyGulchClippyTraversal",

    # Glitches: Tubba's Castle
    "BowlessTubbasCastle",
    "TubbasTableLakiJumpClock",
    "TubbasTableLakiJumpStudy",
    "TubbasTableUltraBoots",
    "TubbasCastleSuperBootsSkip",
    "JumplessMegaRush",
    "ParakarrylessMegaRush",

    # Glitches: Toy Box
    "ParakarrylessBlueBuildingStarPiece",
    "GourmetGuySkipJump",
    "GourmetGuySkipLaki",
    "GourmetGuySkipParakarry",
    "BowlessGreenStation",
    "ClippyGreenStationCoinBlock",
    "KooperlessRedStationShootingStar",
    "GearlessRedStationShootingStar",
    "ParakarrylessBlueBlockCityGap",
    "BlueSwitchSkipLaki",
    "BlueSwitchSkipUltraBoots",
    "RedBarricadeSkip",
    "WattlessDarkRoom",
    "HammerlessBlueStationLaki",
    "HammerlessPinkStationLaki",

    # Glitches: Jade Jungle
    "RaphSkipEnglish",
    "RaphSkipParakarry",
    "RaphSkipLakilester",
    "Ch5SushieGlitch",
    "SushielessJungleStarpieceAndLetter",
    "JumplessDeepJungleLaki",
    "JumplessDeepJungleLedge",

    # Glitches: Mt. Lavalava
    "KooperlessLavalavaPowBlockParakarry",
    "KooperlessLavalavaPowBlockSuperBoots",
    "JumplessLavalavaPowBlock",
    "UltraHammerSkip",
    "UltraHammerSkipLaki",
    "UltraHammerSkipSushie",
    "Flarakarry",
    "ParakarrylessFlarakarryLaki",
    "VolcanoSushieGlitch",
    "VolcanoSushieGlitchGoombario",

    # Glitches: Flower Fields
    "EarlyLakiLZS",
    "EarlyLakiBombettePush",
    "LakilessElevatorRoom",
    "BombettelessMegaSmash",
    "SunTowerSkip",
    "YellowBerryGateSkipLZS",
    "YellowBerryGateSkipLaki",
    "YellowBerryGateSkipBombettePush",
    "RedBerryGateSkipBombettePush",
    "RedBerryGateSkipLaki",
    "BlueBerryGateSkipBombettePush",
    "BlueBerryGateSkipLaki",
    "BubbleBerryTreeLakiJump",
    "BubbleBerryTreeUltraBoots",

    # Glitches: Shiver Region
    "MurderSolvedEarlyLaki",
    "MurderSolvedEarlyBombettePush",
    "Ch7SushieGlitch",
    "StarStoneWithCh7SushieGlitch",
    "ShiverMountainHiddenBlockWithoutUltraBootsLaki",
    "ShiverMountainHiddenBlockWithoutUltraBootsNoLaki",
    "SnowmenSkipLaki",
    "ShiverMountainSwitchSkip",
    "SushielessWarehouseKeyBombette",
    "SushielessWarehouseKeyKooper",

    # Glitches: Crystal Palace
    "MirrorClip",
    "KooperPuzzleSkip",
    "BombettePuzzleSkip",

    # Glitches: Bowser's Castle
    "BowlessBowsersCastleBasement",
    "WattlessDarkBasement",
    "BasementSkipParakarry",
    "BasementSkipLakilester",
    "BasementSkipHammer",
    "BowsersCastleHub1StairClip",
    "BombettelessBowsersCastleBasement",
    "FastFloodRoomKooper",
    "FastFloodRoomKooperless",
    "FastFloodRoomBombetteUltraBoots",
    "Cannonless",

    # Glitches: Global
    "BreakStoneBlocksWithUltraBoots",
    "HammerClipItemGrab",
    "BreakYellowBlocksWithSuperBoots",
    "KnowsHiddenBlocks",
    "KnowsPuzzleSolutions",
    "ReachHighBlocksWithSuperBoots",
]