seed_hash_item_names = [
	"Lucky Star",
	"First Degree Card",
	"Second Degree Card",
	"Third Degree Card",
	"Fourth Degree Card",
	"Diploma",
	"Ultra Stone",
	"Koopa Fortress Key",
	"Ruins Key",
	"Pulse Stone",
	"Tubba Castle Key",
	"Crystal Palace Key",
	"Lunar Stone",
	"Pyramid Stone",
	"Diamond Stone",
	"Volcano Vase",
	"Kooper Shell",
	"Bowser Castle Key",
	"Forest Pass",
	"Boo Weight",
	"Boo Portrait",
	"Crystal Berry",
	"Mystical Key",
	"Storeroom Key",
	"Toy Train",
	"Boo Record",
	"Frying Pan",
	"Dictionary",
	"Mystery Note",
	"Suspicious Note",
	"Crystal Ball",
	"Screwdriver",
	"Cookbook",
	"Jade Raven",
	"Magical Seed 1",
	"Magical Seed 2",
	"Magical Seed 3",
	"Magical Seed 4",
	"Toad Doll",
	"Calculator",
	"Snowman Bucket",
	"Snowman Scarf",
	"Red Key",
	"Blue Key",
	"Letter01",
	"Artifact",
	"Dolly",
	"Water Stone",
	"Magical Bean",
	"Fertile Soil",
	"Miracle Water",
	"Baking Sugar",
	"Baking Salt",
	"Baking Egg",
	"Baking Cream",
	"Baking Strawberry",
	"Baking Butter",
	"Baking Cleanser",
	"Baking Water",
	"Baking Flour",
	"Baking Milk",
	"Lyrics",
	"Melody",
	"Mailbag",
	"Peach Key",
	"Star Stone",
	"Sneaky Parasol",
	"Koot Tape",
	"Koot Koopa Legends",
	"Koot Luigi Autograph",
	"Koot Empty Wallet",
	"Koot Merluvlee Autograph",
	"Koot Shell",
	"Koot Old Photo",
	"Koot Glasses",
	"Koot Package",
	"Koot Red Jar",
	"Silver Credit",
	"Gold Credit",
	"Fire Flower",
	"Snowman Doll",
	"Thunder Rage",
	"Shooting Star",
	"Thunder Bolt",
	"Pebble",
	"Dusty Hammer",
	"Insecticide Herb",
	"Stone Cap",
	"Tasty Tonic",
	"Mushroom",
	"Volt Shroom",
	"Super Shroom",
	"Dried Shroom",
	"Ultra Shroom",
	"Sleepy Sheep",
	"POW Block",
	"Hustle Drink",
	"Stop Watch",
	"Whackas Bump",
	"Apple",
	"Life Shroom",
	"Mystery",
	"Repel Gel",
	"Fright Jar",
	"Please Come Back",
	"Dizzy Dial",
	"Super Soda",
	"Lemon",
	"Lime",
	"Blue Berry",
	"Red Berry",
	"Yellow Berry",
	"Bubble Berry",
	"Jammin Jelly",
	"Maple Syrup",
	"Honey Syrup",
	"Goomnut",
	"Koopa Leaf",
	"Dried Pasta",
	"Dried Fruit",
	"Strange Leaf",
	"Cake Mix",
	"Egg",
	"Coconut",
	"Melon",
	"Stinky Herb",
	"Iced Potato",
	"Spicy Soup",
	"Apple Pie",
	"Honey Ultra",
	"Maple Ultra",
	"Jelly Ultra",
	"Koopasta",
	"Fried Shroom",
	"Shroom Cake",
	"Shroom Steak",
	"Hot Shroom",
	"Sweet Shroom",
	"Yummy Meal",
	"Healthy Juice",
	"Bland Meal",
	"Deluxe Feast",
	"Special Shake",
	"Big Cookie",
	"Cake",
	"Mistake",
	"Koopa Tea",
	"Honey Super",
	"Maple Super",
	"Jelly Super",
	"Spaghetti",
	"Egg Missile",
	"Fried Egg",
	"Honey Shroom",
	"Honey Candy",
	"Electro Pop",
	"Fire Pop",
	"Lime Candy",
	"Coco Pop",
	"Lemon Candy",
	"Jelly Pop",
	"Strange Cake",
	"Kooky Cookie",
	"Frozen Fries",
	"Potato Salad",
	"Nutty Cake",
	"Maple Shroom",
	"Boiled Egg",
	"Yoshi Cookie",
	"Jelly Shroom",
	"Spin Smash",
	"Multibounce",
	"Dodge Master",
	"Power Bounce",
	"Spike Shield",
	"First Attack",
	"Quake Hammer",
	"Double Dip",
	"Sleep Stomp",
	"Fire Shield",
	"Quick Change",
	"D Down Pound",
	"Dizzy Stomp",
	"Smash Charge",
	"Pretty Lucky",
	"Feeling Fine",
	"Attack FX A",
	"Allor Nothing",
	"HP Drain",
	"Jump Charge",
	"Slow Go",
	"Mega Rush",
	"Ice Power",
	"Pay Off",
	"Money Money",
	"Chill Out",
	"Zap Tap",
	"Berserker",
	"Right On",
	"Runaway Pay",
	"Refund",
	"Triple Dip",
	"Hammer Throw",
	"Mega Quake",
	"Smash Charge",
	"Jump Charge",
	"S Smash Chg",
	"S Jump Chg",
	"Power Rush",
	"Auto Jump",
	"Auto Smash",
	"Crazy Heart",
	"Last Stand",
	"Close Call",
	"P Up D Down",
	"Lucky Day",
	"Mega HP Drain",
	"P Down D Up",
	"Power Quake",
	"Auto Multibounce",
	"Flower Fanatic",
	"Heart Finder",
	"Flower Finder",
	"Spin Attack",
	"Dizzy Attack",
	"I Spy",
	"Speedy Spin",
	"Bump Attack",
	"Power Jump",
	"Super Jump",
	"Mega Jump",
	"Power Smash",
	"Super Smash",
	"Mega Smash",
	"Shrink Smash",
	"Kaiden",
	"DDown Jump",
	"Shrink Stomp",
	"Earthquake Jump",
	"Deep Focus",
	"HP Plus",
	"FP Plus",
	"Flower Saver",
	"Damage Dodge",
	"Power Plus",
	"Defend Plus",
	"Happy Heart",
	"Happy Flower",
	"Group Focus",
	"Peekaboo",
	"Attack FX D",
	"Attack FX B",
	"Attack FX E",
	"Attack FX C",
	"Attack FX F",
	"Healthy Healthy",
	"Heart",
	"Coin",
	"Star Point",
	"Heart Point",
	"Flower Point",
	"Star Piece",
	"Cake Done",
	"Cake Bare",
	"Cake Pan",
	"Cake Batter",
	"Cake Bowl",
	"Cake Mixed",
	"Cake With Icing",
	"Cake With Berries",
	"Hammer",
	"Super Hammer",
	"Ultra Hammer",
	"Boots",
	"Super Boots",
	"Ultra Boots",
]

def get_items_from_seed_id(seed_id: int):
	seed_bytes = seed_id.to_bytes(4, 'big')
	return [
		seed_hash_item_names[seed_bytes[0]],
		seed_hash_item_names[seed_bytes[1]],
		seed_hash_item_names[seed_bytes[2]],
		seed_hash_item_names[seed_bytes[3]]
	]