# Generated by Django 4.0.1 on 2022-01-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer_server', '0005_alter_setting_initialcoins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='BlocksMatchContent',
        ),
    ]
