# Generated by Django 4.0.1 on 2022-01-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer_server', '0008_setting_quizmoalwaysappears_setting_romannumerals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AddField(
            model_name='setting',
            name='SeedID',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='ColorA',
            field=models.BigIntegerField(default=3957749759),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ColorB',
            field=models.BigIntegerField(default=2388272639),
        ),
    ]
