# Generated by Django 4.0.1 on 2022-02-01 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer_server', '0009_remove_setting_id_setting_seedid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='CreationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
