# Generated by Django 4.0.1 on 2022-01-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0006_remove_setting_blocksmatchcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ProgressiveScaling',
            field=models.BooleanField(default=False),
        ),
    ]
