# Generated by Django 4.0.1 on 2022-01-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0007_setting_progressivescaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='QuizmoAlwaysAppears',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='RomanNumerals',
            field=models.BooleanField(default=False),
        ),
    ]
